name: libraries

on: workflow_dispatch

jobs:
  install-published:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Poetry
        uses: snok/install-poetry@main
      - name: Install dependencies
        run: poetry install
        working-directory: py/test/self
      - run: ./cli/setup.sh login-serverless adb-2367537008441771.11.azuredatabricks.net ${{secrets.PAT}}
      - run: poetry run pytest
        working-directory: py/test/self