name: libraries

on: push

jobs:
  install-published:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Poetry
        uses: snok/install-poetry@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless adb-2367537008441771.11.azuredatabricks.net ${{secrets.PAT}}
      - name: Install dependencies
        run: poetry install
        working-directory: py/test/self
      - run: python test.py
        working-directory: py/test/self