name: Python on push

on: push

jobs:
  self-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Poetry
        uses: snok/install-poetry@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{secrets.PAT}}
      - name: Install dependencies
        run: poetry install --all-extras
        working-directory: py/test/self
      - run: poetry run python test.py
        working-directory: py/test/self
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install Poetry
        uses: snok/install-poetry@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{secrets.PAT}}
      - name: Install dependencies
        run: poetry install --all-extras
        working-directory: py
      - run: poetry run test
        working-directory: py