name: Python

on:
  workflow_dispatch:
  push:

jobs:
  self-reference:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@main
      - if: runner.os == 'Windows'
        run: |
          ./cli/setup.ps1 Install
          ./cli/setup.ps1 Connect-Serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - if: runner.os == 'Linux'
        run: |
          ./cli/setup.sh install
          ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - uses: astral-sh/setup-uv@main
        with:
          version: "latest"
      - run: uv sync --all-extras
        working-directory: py/tests/self
      - run: uv run python test.py
        working-directory: py/tests/self
      - run: uv run databricks-connect test
        working-directory: py/tests/self
  tests:
    runs-on: ubuntu-latest
    needs: self-reference
    steps:
      - uses: actions/checkout@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest --ignore=integration --ignore=mlflow
          tests: py/tests
          version: 3.12 # hardcode is required due to error: Python versions in the Spark Connect client and server are different
        env:
          CATALOG: ${{vars.CATALOG}}
          AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  gcp:
    runs-on: ubuntu-latest
    environment: gcp
    needs: tests
    steps:
      - uses: actions/checkout@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: pytest integration/gcp_test.py
          tests: py/tests
          version: 3.12 # hardcode is required due to error: Python versions in the Spark Connect client and server are different
        env:
          PYTHONPATH: py
          CLIENT_EMAIL: ${{vars.CLIENT_EMAIL}}
          CLIENT_ID: ${{vars.CLIENT_ID}}
          PRIVATE_KEY_ID: ${{vars.PRIVATE_KEY_ID}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}