name: Python

on:
  workflow_dispatch:
  push:

jobs:
  self-reference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - uses: astral-sh/setup-uv@main
        with:
          version: "latest"
      - run: uv sync --all-extras
        working-directory: py/tests/self
      - run: uv run python test.py
        working-directory: py/tests/self
      - run: uv run databricks-connect test
        working-directory: py/tests/self
  tests:
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - uses: actions/checkout@main
      - run: ./cli/setup.sh install
      - run: ./cli/setup.sh login-serverless ${{ vars.WORKSPACE }} ${{ secrets.PAT }}
      - uses: davidkhala/uv-buildpack@main
        with:
          working-directory: py
          test-entry-point: test
          tests: py/tests
        env:
          CLIENT_EMAIL: ${{vars.CLIENT_EMAIL}}
          CLIENT_ID: ${{vars.CLIENT_ID}}
          PRIVATE_KEY_ID: ${{vars.PRIVATE_KEY_ID}}
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          NEW_RELIC_LICENSE_KEY: ${{secrets.NEW_RELIC_LICENSE_KEY}}